[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "blueprint_stocks_timerange"
version = "0.1.0"
requires-python = ">=3.8"
readme = "README.md"
dependencies = ["humanize", "rerun-sdk", "yfinance"]

[project.scripts]
blueprint_stocks_timerange = "blueprint_stocks_timerange:main"

[tool.rerun-example]
#skip = true
