[project]
name = "dna"
version = "0.1.0"
# requires-python = "<3.12"
readme = "README.md"
dependencies = [
    "numpy",
    "rerun-sdk",
    "scipy"
]

[project.scripts]
dna = "dna:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
