[project]
name = "nuscenes_dataset"
version = "0.1.0"
readme = "README.md"
dependencies = [
  "matplotlib>=3.8.2",
  "numpy",
  "nuscenes-devkit",
  "requests",
  "rerun-sdk"
]

[project.scripts]
nuscenes_dataset = "nuscenes_dataset.__main__:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
