[project]
name = "log_file"
version = "0.1.0"
# requires-python = "<3.12"
readme = "README.md"
dependencies = [
    "rerun-sdk"
]

[project.scripts]
log_file = "log_file:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
