[project]
name = "blueprint"
version = "0.1.0"
# requires-python = "<3.12"
dependencies = ["numpy", "rerun-sdk"]

[project.scripts]
blueprint = "blueprint:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
