[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "human_pose_tracking"
version = "0.1.0"
requires-python = ">=3.8,<3.12"  # TODO(ab): relax when mediapipe supports 3.12
readme = "README.md"
dependencies = [
  "mediapipe==0.10.11",
  "numpy",
  "opencv-python>4.6", # Avoid opencv-4.6 since it rotates images incorrectly (https://github.com/opencv/opencv/issues/22088)
  "requests>=2.31,<3",
  "rerun-sdk",
]



[project.scripts]
human_pose_tracking = "human_pose_tracking:main"

[tool.rerun-example]
skip = false