[project]
name = "arkit_scenes"
version = "0.1.0"
# requires-python = "<3.12"
readme = "README.md"
dependencies = [
    "matplotlib>=3.8.2",
    "numpy",
    "opencv-python",
    "pandas",
    "rerun-sdk",
    "scipy",
    "tqdm",
    "trimesh"
]

[project.scripts]
arkit_scenes = "arkit_scenes.__main__:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
