[project]
name = "multiprocess_logging"
version = "0.1.0"
readme = "README.md"
dependencies = [
  "rerun-sdk"
]

[project.scripts]
multiprocess_logging = "multiprocess_logging:main"

# [tool.rerun-example]
# skip = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
